-- Add updatedAt (last-changed) to every entity. ADDITIVE: add column, backfill from createdAt.
ALTER TABLE "Organization" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Organization" SET "updatedAt" = "createdAt";
ALTER TABLE "CustomTrip" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "CustomTrip" SET "updatedAt" = "createdAt";
ALTER TABLE "CustomItem" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "CustomItem" SET "updatedAt" = "createdAt";
ALTER TABLE "ActivityLog" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "ActivityLog" SET "updatedAt" = "createdAt";
ALTER TABLE "VisaApplicant" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "VisaApplicant" SET "updatedAt" = "createdAt";
ALTER TABLE "User" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "User" SET "updatedAt" = "createdAt";
ALTER TABLE "Trip" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Trip" SET "updatedAt" = "createdAt";
ALTER TABLE "Night" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Night" SET "updatedAt" = "createdAt";
ALTER TABLE "HotelBooking" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "HotelBooking" SET "updatedAt" = "createdAt";
ALTER TABLE "Car" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Car" SET "updatedAt" = "createdAt";
ALTER TABLE "Inclusion" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Inclusion" SET "updatedAt" = "createdAt";
ALTER TABLE "Customer" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Customer" SET "updatedAt" = "createdAt";
ALTER TABLE "Booking" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Booking" SET "updatedAt" = "createdAt";
ALTER TABLE "Traveller" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Traveller" SET "updatedAt" = "createdAt";
ALTER TABLE "PendingPayment" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "PendingPayment" SET "updatedAt" = "createdAt";
ALTER TABLE "VendorBooking" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "VendorBooking" SET "updatedAt" = "createdAt";
